# Generated by Django 6.0.3 on 2026-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=6),
        ),
    ]
